
[general]
pidfile="burrows.pid"

[logging]
filename="/home/helios/go/logs/burrow.log"
level="info"

[zookeeper]
servers=["localhost:2181"]
#root-path="/burrow-test"
timeout=30

[httpserver.mine]
address=":8080"

[storage.default]
class-name="inmemory"
intervals=5
min-distance=1

[evaluator.default]
class-name="caching"
expire-cache=60

[client-profile.notls]
client-id="burrow-test"
#kafka-version="1.0.0"

[cluster.tracking]
class-name="kafka"
servers=["localhost:9092"]
client-profile="notls"
topic-refresh=60

[consumer.tracking_kafka]
class-name="kafka"
cluster="tracking"
servers=["localhost:9092"]
client-profile="notls"

[consumer.tracking_zk]
class-name="kafka_zk"
cluster="tracking"
servers=["localhost:2181"]
#zookeeper-path="/kafka-tracking"
zookeeper-timeout=30
